version: "3"

services:
  api:
    container_name: api
    build: ./api
    command: npm start
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./api:/usr/volum1
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    command: yarn start
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/usr/app/
      - /usr/app/node_modules   
    links:
      - api 
  # nginx:
  #     container_name: staticfiles
  #     image: nginx:1.13.12-alpine
  #     ports:
  #       - "80:80"
  #       - "443:443"
  #     environment:
  #       - NGINX_PORT=80
  #     volumes:
  #       - ./html-page:/var/www/
  #       - ./html-page/nginx.conf:/etc/nginx/conf.d/default.conf
  # app:
  #     container_name: webserver
  #     image: nginx:1.13.12-alpine
  #     ports:
  #       - "80:80"
  #       - "443:443"
  #     environment:
  #       - NGINX_PORT=80
  #     volumes:
  #       - ./app/build:/var/www/
  #       - ./app/nginx.conf:/etc/nginx/conf.d/default.conf
  # myApp:
  #   image: myapp:1.0
  #   container_name: my-app
  #   build: ./app
  #   ports:
  #     - 80:80