version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    working_dir: /usr/volum1
    ports:
      - '3000:3000'
    #environment:
     # - NODE_ENV=development
    volumes:
      - .:/usr/volum1
      - /usr/volum1/node_modules

          